apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend # jo uper selector m label define kia h yha bh yh use krna ha
    spec:
      containers:
      - name: chatapp-backend
        image: jrnaimat/chatapp-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV 
          value: production
        - name: MONGODB_URI
          value: mongodb://mongoadmin:secret@mongodb:27017/?authSource=admin
        - name: JWT_SECRET
          valueFrom:
           secretKeyRef:
             key: jwt
             name: chatapp-secrets
        - name: PORT
          value: "5001"
          